### ISSUE TITLE
Remove mocha and use built-in rspec mocking library

### ISSUE THREAD

**Issue by ajm188** [thoughtbot/factory_girl#1015]

**Comment by odlp** [comment]
Sounds like a good idea. One less dev dependency and Mocha does seem to trample the world:
https://github.com/freerange/mocha/blob/cedcd94ebbad2adedfd72300e4bcca4660afb216/lib/mocha/api.rb#L19:L21

Whereas RSpec can be monkey-patch free since `3.0`:
https://relishapp.com/rspec/rspec-core/v/3-0/docs/configuration/zero-monkey-patching-mode

**Comment by odlp** [comment]
Cross-linking to PR #1016

**Comment by odlp** [comment]
Fixed via #1016
