### ISSUE TITLE
Why the name change from factory_girl to factory_bot?

### ISSUE THREAD

**Issue by KurtRMueller** [thoughtbot/factory_girl#1053]
Just curious. The explanation is not up yet in the repo.

I realize the software is free, open-source, and provided as is and you absolutely owe me nothing. In fact, I probably owe every developer at Thoughtbot a beer or three (or another beverage of your choice).

I however have coming to lovingly refer to the gem as Factory Girl over the years. Things change and I'll be lovingly referring to the gem as Factory Bot in the next couple of years.

Anyway, thanks for the great work y'all do. My apologies for taking up your time on this trivial issue.

**Comment by joshuaclayton** [comment]
@KurtRMueller thanks for reaching out! We're in the process of making the appropriate changes, but https://github.com/thoughtbot/factory_girl/issues/921 is a great place to start, and the primary driver for a conversation both with the community and an internal conversation within the company. We'll be making more documentation changes within the repository, as well as a blog post, to outline the drivers behind the change in the coming days. Until then, we appreciate your patience!

And if you're around any of our offices and want to say hi to the local team, don't hesitate to reach out; I'm sure there are plenty who'd be up for grabbing a beer 😄 

Because we'll be having this conversation in other areas, I'd encourage you to keep your eyes peeled; in the meantime, I'll close this issue specifically, since the one above is our primary method of communication on GH about the change.

Again, thanks for your patience as we roll these changes out!

**Comment by nisevi** [comment]
@KurtRMueller here: https://robots.thoughtbot.com/factory_bot :+1:

**Comment by senguttuvang** [comment]
In laymen terms, the term, `factory girl` looks like projecting women as baby creating machines and hence feminists would have opposed the names, hence the name change.

**Comment by bauerd** [comment]
Thanks for making me search and replace both my Gemfile und application source code just to get rid of the god-damn deprecation warning. Pointless
