### ISSUE TITLE
has_many and build_stubbed doesn't automatically make association

### ISSUE THREAD

**Issue by derrickmar** [thoughtbot/factory_girl#784]
It seems appropriate that factory girl should make the stubbed has_many association automatically when an associated object is assigned to it. Right now (in ```factory_girl 4.5.0```) it does not.

```ruby
context "some description" do
      let!(:qs) { build_stubbed(:question) }
      # assign as associated object with qs
      let!(:evaluation) { build_stubbed(:evaluation, question: qs)}
      subject { qs }

      it "should be considered ungraded" do
        # This fails! qs.evaluations 
        expect(qs.evaluations.empty?).to be(false)
      end
    end
```

In order for this to work we have to stub.
```ruby
      before(:each) do
        qs.stub(:evaluations).and_return([evaluation])
      end
```

**Comment by entrity** [comment]
:+1:

**Comment by derrickmar** [comment]
Was wondering if there are any updates to this. Thanks!

**Comment by Quintasan** [comment]
[Apparently](http://stackoverflow.com/questions/17754770/factorygirl-build-stubbed-strategy-with-a-has-many-association) this is not a good idea. Can we have some input on this?

**Comment by joshuaclayton** [comment]
@derrickmar there's not a great way to do this, since FG doesn't recreate the entire ActiveRecord interface for stubs.

In cases like this, it might be more straightforward to create the records, since you're relying on the associations themselves to determine the data. Alternatively, if you had a `EvaluationsCalculator` class that was instantiated with a list of evaluations and had instance methods for ungraded items etc, you should be able to test by passing in a list of stubbed evaluations.
