### ISSUE TITLE
create_list with different values for the same attribute

### ISSUE THREAD

**Issue by sohymg** [thoughtbot/factory_girl#787]
Is there any way to use create_list with different values for the same attribute?

for eg. I would like to do something like 
`FactoryGirl.create_list(:student, 2, gender: [male, female])`
and it will give me 2 students with 1 male 1 female

**Comment by Mohit-Pawar** [comment]
@sohymg 
No there is no way to use create_list with different values for the same attribute

**Comment by syedrakib** [comment]
fast-forward 3 years..... is this still not possible with factory bot?

**Comment by joshuaclayton** [comment]
@syedrakib FB + Ruby should work well in situations like this:

```ruby
%w(NYC Boston SF Austin).map do |tb_location|
  FactoryBot.create(:location, city: tb_location)
end
```

**Comment by emmanuelgautier1994** [comment]
Since [v5.2.0](https://github.com/thoughtbot/factory_bot/releases/tag/v5.2.0) you can do this:
```
twenty_somethings = create_list(:user, 10) do |user, i|
  user.date_of_birth = (20 + i).years.ago
end
```

**Comment by juniorjp** [comment]
@emmanuelgautier1994 that is good, but I just noticed it doesn't persist the setted attribute, unless I call .save manually. Siince it's `create_list` method, I expected it to be automacally saved with other attributes

**Comment by composerinteralia** [comment]
@juniorjp I see why you might expect that, but the block passed to any strategy will always yield the complete, already-built object. For the singular methods, it identical to using `tap`:

```rb
create(:user).tap do |user|
end
``

For the `*_list` methods it ends up being roughly equivalent to using `each`:

```rb
create_list(:user, 10).each do |user|
end
```

The feature added here offers something like `each_with_index`:

```rb
create_list(:user, 10).each_with_index do |user, i|
end
```

We could probably do a better job of documenting this behavior.

**Comment by hernamvel** [comment]
I just posted a quick article inspired in this thread and the implications of the decision taken of yielding the created object to the block, specially when dealing with active record validations like presence or uniqueness. Hope this can help:

 https://dev.to/hernamvel/the-optimal-way-to-create-a-set-of-records-with-factorybot-createlist-factorybot-buildlist-1j64

**Comment by composerinteralia** [comment]
Nice! I think that does a nice job of showing how that block works. If you are interested in working some of that into the documentation, I'd certainly welcome a PR.

One thought about that particular example—I might have used a [sequence](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#sequences) to ensure uniqueness of `employee_number`, rather than setting the number manually each time. That way you could do `create_list(:employee, 20)` and you'd get 20 different sequential employee numbers.

**Comment by hernamvel** [comment]
Hey @composerinteralia thanks for your feedback, and yeah, my purpose was mainly to show have the block worked and just needed this employee_number only for the sake of building the example, but I agree that a sequence might fit better here. Not sure in which part of documentation will fit this explanation, but I will try to make a better look.

**Comment by entrity** [comment]
I observe that are nice ways to code the creation of multiple records with `*_list`, but it looks as if each of them will make a separate db write for each record instead of a single mass insert the way that `create` can, e.g. `User.create([{ first_name: 'Jamie' }, { first_name: 'Jeremy' }])`.

Unless I'm mistaken, I think it's worth reducing the number of db writes in order to reduce execution time of large test suites. I would re-open this issue.
