### ISSUE TITLE
Problems factory_girl faker data in has_many associations

### ISSUE THREAD

**Issue by VoTaiTri** [thoughtbot/factory_girl#789]
I'm new rspec test and factory_girl, help me that problem, please!
I have 3 models User, Review and Activity look like
```ruby
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_many :activities, dependent: :destroy
end

class Review < ActiveRecord::Base
  belongs_to :user
end

class Activity < ActiveRecord::Base
  belongs_to :user
  
  validates :target_id, presence: true
  validates :action_type, presence: true
```
model Activity to save activity of each user. In this case, activity is reviewing. Whenever user create a new record in reviews table, the system also creates a record in activities table (target_id = review_id , action_type = "review")
Now, when i write rspec test for User model, i need test for association User has_many Activity. So how can i faker data of model User, Review and Activity by factory_girl to do that???
Thanks!!!

**Comment by jsom** [comment]
Hello @VoTaiTri. It sounds like you're writing a unit test for the User model. Instead of using factory_girl have you considered using [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers)?

```ruby
describe User do
  it { should have_many(:activities) }
end
```

Or are you trying to test that a Review is actually created for a User and saved in to the Activity association by your application?

**Comment by VoTaiTri** [comment]
Thanks @jsom
I solved that problem by gem 'shoulda-matchers'
