### ISSUE TITLE
Getting Started Documentation Page is Broken

### ISSUE THREAD

**Issue by dmill** [thoughtbot/factory_girl#806]
http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md is broken

**Comment by TedStudley** [comment]
I had the same issue, so I looked into it. The screen renders properly for a split-second, then turns into this:
<img width="1131" alt="screen shot 2015-09-01 at 11 54 56 am" src="https://cloud.githubusercontent.com/assets/1839547/9613458/53392a26-50a0-11e5-8065-bed9d446e7ff.png">
as you can probably tell, this makes the documentation pretty unusable.

Stepping through using the developer console showed that the issue was being caused by a file titled `markdownify.js`, but this file isn't being served by rubydoc. I tracked it down to a Chrome extension that I have installed, [markdown-preview](https://chrome.google.com/webstore/detail/markdown-preview/jmchmkecamhbiokiopfpnfgbidieafmd). Not sure if this also explains your situation, but this issue doesn't seem to be caused (or fixable) by factory_girl.

**Comment by drapergeek** [comment]
Thanks for the reply @TedStudley 

If you continue to have issues with only FactorGirl, please let us know @dmill
