### ISSUE TITLE
attributes_for returns reference to defined value

### ISSUE THREAD

**Issue by joenas** [thoughtbot/factory_girl#818]
I'm not sure if this is the expected behavior or not, but it is possible to manipulate values returned by `attributes_for`, which will then be returned when calling the method again.

Example

```ruby
require 'factory_girl'
require 'json'
include FactoryGirl::Syntax::Methods

class Test
end

FactoryGirl.define do
  factory :test do
    body JSON.parse('{"key": "value"}')
  end
end

a = attributes_for(:test)
puts "a: #{a}"

attrs = attributes_for(:test)
attrs[:body].merge!("key" => :other)
b = attrs
puts "b: #{b}"

c = attributes_for(:test)
puts "c: #{c}"

attrs = attributes_for(:test) do |_attrs|
  _attrs[:body].merge!("key" => :whut)
end
d = attrs
puts "d: #{d}"

e = attributes_for(:test)
puts "e: #{e}"
```

Result
```
$ ruby fg_test.rb
a: {:body=>{"key"=>"value"}}
b: {:body=>{"key"=>:other}}
c: {:body=>{"key"=>:other}}
d: {:body=>{"key"=>:whut}}
e: {:body=>{"key"=>:whut}}
```
This can of course be prevented with `body {JSON.parse('{"key": "value"}')}` but to me it was not expected.

**Comment by joshuaclayton** [comment]
@joenas yes, you're correct - because virtually everything in Ruby is mutable, it's easy to demonstrate this behavior with arrays, hashes, and strings (since those are the easiest to mutate). By wrapping the attribute in a block, it's evaluated every time the factory is run, meaning that the underlying data structure can't be mutated.

I've actually considered disallowing non-lazy attributes so developers aren't bitten by this, but it's a massive (breaking) change that likely also has performance implications.
