### ISSUE TITLE
Prevent deprecated callbacks from accidentally calling them

### ISSUE THREAD

**Issue by vemv** [thoughtbot/factory_girl#827]
One can freely call `after_build, after_create, before_create`, causing weird issues to happen.

I occasionally type `after_build` instead of `after(:build)` by pure mistake, not for legacy reasons.

Make these methods protected/whatever? Hypothetical legacy users could just call them explicitly (maybe with `send`...).

Thanks!

Victor

**Comment by joshuaclayton** [comment]
@vemv any ideas for approaches here? Given how FG's internals handle attributes (by capturing everything), technically virtually everything *can* be written within the definitions themselves. I think going out of the way to call out potentially wrong attributes means maintaining a fairly large list.

Currently, I imagine the failure you're seeing is that it can't call `after_create=` on the instance; the alternative would be to introduce additional code to deliver a similar (but different) message stating roughly the same thing; because I'm a maintainer, I obviously prefer introducing less code over more code, but I'd love ideas if you have any to improve this.

**Comment by vemv** [comment]
> Currently, I imagine the failure you're seeing is that it can't call after_create= on the instance;

Indeed, that's the case as of today!

Back when I opened this issue, the message/backtrace was much more long/confusing.

Maybe something has changed since Oct 4? Or maybe the unclear backtraces only happen under conditions that I can't reproduce anymore.

Closing!
