### ISSUE TITLE
Mocking ActiveSupport::Notifications#instrument breaks factory girl

### ISSUE THREAD

**Issue by vinniefranco** [thoughtbot/factory_girl#829]
If you have the following within your spec
```ruby
allow(ActiveSupport::Notification).to receive(:instrument)
```
any factory girl build/creation methods ran after the mock will return nil since it causes FactoryGirls internals to return nil instead of the result of `factory#run`

https://github.com/thoughtbot/factory_girl/blob/95c6d96306fe90e6ef83f6b80f67d206b4da4a37/lib/factory_girl/factory_runner.rb#L28

**Comment by vemv** [comment]
Well of course if you break code (with the stubbing mechanism), dependent code will break. Not a FG issue.

Use `and_call_original`

allow(ActiveSupport::Notification).to receive(:instrument).once.and_call_original

**Comment by vinniefranco** [comment]
@vemv I was just mentioning because it caused a snag with us. We were working on our own internal instrumentation, just making sure that `ActiveSupport::Notification` received the correct message and it took a bit to realize why factories were broken.

**Comment by vemv** [comment]
Yeah, these things happen.

I don't see a reason to maintain an issue open though!

**Comment by joshuaclayton** [comment]
@vinniefranco yep, it's tricky - stubbing is one of those things that's actually fairly difficult to get right because it's very broad-sweeping. In your case, another way to ensure instrumentation is working correctly would be to inject that code as a dependency and then test against that. This ensures that the code you're testing is entirely isolated (because you own what's being passed in). I discuss dependency injection with class attributes here: https://robots.thoughtbot.com/segment-io-and-ruby; hopefully it'll be of some help, at least as a reference for how to approach DI.

**Comment by vinniefranco** [comment]
@joshuaclayton thanks for the suggestion! I ended up wrapping ActiveSupport::Notifications in a object that I owned, so I could verify that the command I was sending was correct.

**Comment by joshuaclayton** [comment]
@vinniefranco awesome, glad to hear it worked for you! It's an approach that definitely takes a bit getting used to, but I've found it makes tests that much easier to write :-)
