### ISSUE TITLE
FactoryGirl.lint apperas to be a messy housemate

### ISSUE THREAD

**Issue by impurist** [thoughtbot/factory_girl#848]
Does the "FactoryGirl.lint" method intend to create and leave records in the database?
It sure seems to leave a mess behind and causes validation failure which forces the ridiculous use of sequence...  
I removed all create calls in my tests and FG still creates records 
The ONLY reason a factory should create a record is when a developer calls create.
OR 
I am a complete fool, missing some important point and you guys know better.

My factories work fine when I do this
      # FactoryGirl.lint

**Comment by Mohit-Pawar** [comment]
Points to note about FactoryGirl.lint
1.FactoryGirl.lint builds each factory and subsequently calls #valid? on it (if #valid? is defined); if any calls to #valid? return false, FactoryGirl::InvalidFactoryError is raised with a list of the offending factories. 
2. the most important point 
After calling FactoryGirl.lint, you'll likely want to clear out the database, as built factories will create associated records.

so if you are using FactoryGirl.lint you should do following configuration
# spec/support/factory_girl.rb
RSpec.configure do |config|
  # additional factory_girl configuration

  config.before(:suite) do
    begin
      DatabaseCleaner.start
      FactoryGirl.lint
    ensure
      DatabaseCleaner.clean
      # above is important bcoz FactorGirl.lint will create associated object in database. 
    end
  end
end

**Comment by impurist** [comment]
Thanks for the reply. Thats exactly what I have.
```ruby
RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods

  config.before(:suite) do
    begin
      DatabaseCleaner.start
      FactoryGirl.lint
    ensure
      DatabaseCleaner.clean
    end
  end
end
```

**Comment by joshuaclayton** [comment]
@impurist @Mohit-Pawar when FG lints, it does in fact create records in the database; please see https://github.com/thoughtbot/factory_girl/blob/08c65ebd74dae370513ce57e7a787aae2d0f168b/lib/factory_girl/linter.rb#L56-L77 for the corresponding lines to lint factories and factories with traits.

@impurist your `before(:suite)` code looks good; what behavior are you seeing? If linting prior to a suite run is breaking subsequent tests, it's possible that your test suite has mystery guests or otherwise relies on a particular execution order of tests/factories. As for validation errors, that also seems like a reliance on a particular type of factory execution that will lead to other problems over time.

**Comment by joshuaclayton** [comment]
No response here, so I'm going to close this for now; if there's additional context that can be provided, please feel free to reopen.
