### ISSUE TITLE
Origin of name Factory Girl

### ISSUE THREAD

**Issue by quangv** [thoughtbot/factory_girl#849]
Hey Thoughtbot,

I was wondering where did the name "Factory Girl" come from?

I'm an American, new to RoR, so maybe I don't understand the historical references?

Kind Regards.

----

guess i'm not the only one who is curious. #785

**Comment by Fourfingerz** [comment]
I love this name so much. It's catchy and possibly one of the most memorable names in any software.

**Comment by nikkypx** [comment]
probably inspired by 'rosie the riveter'

**Comment by gkop** [comment]
My theory is it was inspired by the movie [Factory Girl](https://en.wikipedia.org/wiki/Factory_Girl_(film)) about Andy Warhol's muse [Edie Sedgwick](https://en.wikipedia.org/wiki/Edie_Sedgwick).

**Comment by jkrmr** [comment]
Mine is that the 'Girl' in the name comes from [girl friday](https://en.wikipedia.org/wiki/Friday_(fictional_character)#Idiom), while the movie title's circulation in the cultural ether just tipped off the library authors to the euphony of concatenating 'Factory' and 'Girl' like that.

**Comment by mhorne89** [comment]
I know this is an old issue but I think I may have an answer for people who are curious about the origins of this term.

Factory Girl is a name which is used in the UK, most notably in Ireland. It is used to refer to working-class women who worked in factories during the 1900's when women were introduced into the workplace fulfilling roles which were typically held by men (e.g. factory work).

During World War I and II almost all men in the United Kingdom were conscripted and sent over to France/Germany to fight in the war. This left an enormous deficit in the workforce as very little people were left to keep the country running and functioning. As a result, the women who were left behind inherited the responsibility of filling in for the depleted workforce taking up jobs in farming, factory work and other labor-intensive jobs typically assigned to men. Also, the mass production of weapons and ammunition that was required for the war effort were constructed by a female workforce. The significant shift in gender in this typically male profession gave birth to the nickname "Factory Girls".

The nickname "Factory Girl" has always been used as an extremely endearing and empowering term for working women. Icons such as Rosie the Riveter stood as a proud symbol of a generation of strong, capable, willing and highly respected women in history who rose up to prove women were capable of stepping up to overcome the harsh situations of war to support the men fighting the war, do their part in protecting and defending their countries and families, and prove the perceived capabilities of the genders false. After the war, working-class women continued to work in such factory jobs and eventually were fully assimilated into the workplace as equals to men, taking an enormous step forward for women's rights, a truly incredible time in our nations history to be celebrated as both genders worked together (and emerged triumphant) in a common goal to defend the nation and prevent the NSDAP gaining more power in the world, ending the atrocious war crimes being committed.

Unfortunately, a stark contrast to the feminist outlook we see in the modern era after it was hijacked by the middle class to sell music videos and T-shirts, sell ads though clickbait Buzzfeed articles mainly complaining about how men are the problem to { print grievanceWithExBoyfriend }, pushing to widen the gender divide we are now all unwillingly part of, bloggers and gender studies dropouts sitting around complaining that they haven't been approached with a job offer to be CEO of Google yet etc etc.

Now it seems we require to cause completely unnecessary technical complications due to people pretending to be offended by the word "girl" and all the guys who are pathetically posturing to girls because they self-identify as having no other value as a man to display than fake valiant white knight-ing. Censoring the term "Factory Girl" in the name of feminism marks the slow death of intelligent thought in the IT industry and we should speak out against this growing trend if we ever wish to remove this toxic, unintelligent, uneducated and nonsensical style of thought from our industry, our generation, and our wider society in general.
