### ISSUE TITLE
attributes_from evaluates lazy loaded assocation

### ISSUE THREAD

**Issue by KevinSjoberg** [thoughtbot/factory_girl#875]
I have a `booking_proposal` factory. It consists of three relations. A `lessee`, `lessor` and a `product`. My business logic states that the lessor of a booking proposal should be the same as the owner of the product.

To reflect this in my factory I've done the following:

```
FactoryGirl.define do
  factory :booking_proposal do
    price 1000
    state :pending
    start_date { Time.zone.now }
    end_date { Time.zone.now + 7.days }
    lessor { product.user }
    association :lessee, factory: :user
    product
  end
end
```

This works great, except when calling this factory with `attributes_from`. `attributes_from` evaluates the `lessor` and blows up when trying to call `.user` on `product`, since `product` is nil.

My understanding is that `attributes_from` does not include assocations at all so why is `lessor` evaluated?

Any help in the matter are appreciated!

**Comment by joshuaclayton** [comment]
@KevinSjoberg the library ignores associations as you mentioned, but the `lessor` declaration is treated as a normal attribute because it's not declared as `association :lessor` (explicit association) or `lessor` (implicit association).

The two options I can think of would be to either assign the value in an FG callback or check if product is present prior to calling `user` on it.
