### ISSUE TITLE
Inherited traits fail noisily when a trait has the same name as another factory

### ISSUE THREAD

**Issue by georgemillo** [thoughtbot/factory_girl#885]
From https://github.com/thoughtbot/factory_girl/issues/360, I learned that I can create traits that inherit from other traits, which is great. But when I tried to use this in my own app, I couldn't get it to work and kept getting a `NoMethodError`. Eventually I figured out it was because the trait I was inheriting from had the same name as one of my other factories, which was causing a subtle and unintuitive failure.

Here's a slightly contrived example that demonstrates what I mean. Run this script and it will fail with `NoMethodError: undefined method `present=' for #<Employee>`

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '>= 5.0.0.beta3', '< 5.1'
  gem 'sqlite3'
  gem 'factory_girl_rails', '~> 4.6.0'
end
require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'factory_girl'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :presents, force: true do |t|
    t.integer :price
    t.boolean :wrapped
  end

  create_table :employees, force: true do |t|
    t.datetime :arrived_at
    t.boolean  :on_break, default: true
  end
end

class Present < ActiveRecord::Base
end

class Employee < ActiveRecord::Base
end

FactoryGirl.define do
  factory :present do
    price   14_99
    wrapped true
  end

  factory :employee do
    trait :present do
      arrived_at { 5.hours.ago }
    end

    trait :working do
      present
      on_break false
    end
  end
end

class BugTest < Minitest::Test

  def test_factory_traits
    FactoryGirl.create :employee, :working # This line raises an error
    assert_equal Employee.count, 1
    employee = Employee.last
    assert (employee.arrived_at < Time.now)
    refute employee.on_break
  end
end
```

Is there any logical reason why trait names and factory names shouldn't conflict? If there isn't, can the above code be made to work? If there is, can things be changed so that, in my above example, trying to define the trait `:present` will raise a more helpful error, like how when I try to define a *factory* whose name has been taken I get an error that says `factory already defined`?

**Comment by joshuaclayton** [comment]
> Is there any logical reason why trait names and factory names shouldn't conflict?

Yes; FactoryGirl cannot infer whether to use a trait or an association because it doesn't introspect on the object in question to determine behavior.

> If there is, can things be changed so that, in my above example, trying to define the trait :present will raise a more helpful error, like how when I try to define a factory whose name has been taken I get an error that says factory already defined?

I don't believe so; what you're seeing is the behavior of implicit declaration choosing a code path (you can see the logic here: https://github.com/thoughtbot/factory_girl/blob/e84bfeba9b9859ebf0884c0c47f84dd7ded381e1/lib/factory_girl/declaration/implicit.rb#L21-L29). The factory, at this point, has know knowledge of the object being acted upon, so there's no way to inspect its methods to determine the code path.

Generally speaking, I'd avoid naming traits and factories the same for this reason alone. As the application grows, it every single developer either to understand the underlying data structures intimately when interacting with factories (to determine whether `present` is assigning an association (`present`) or an `arrived_at` property) as well as any test using it. It also effectively breaks finding/replacing code since it's not unique to the system.

What probably makes more sense is an explicit failure if a factory and trait are ever named the same thing, regardless of nesting. If you're interested in contributing, that'd actually be a great feature to pull into a 5.0 release. The tricky part would be looking an arbitrary number of levels deep to find all registered traits, since I believe nested traits aren't stored in a global registry (I could be wrong, though!).

**Comment by georgemillo** [comment]
Thanks for the feedback. Just to clarify, when you say:

> What probably makes more sense is an explicit failure if a factory and trait are ever named the same thing, regardless of nesting.

Are you talking about raising an error at the point where the factory is *defined*, or when the factory/trait is *called*? If it's the former, aren't you contradicting yourself? Because that's what I was trying to suggest when I said:

> can things be changed so that, in my above example, trying to define the trait :present will raise a more helpful error

to which you said "I don't believe so". (Apologies if my original wording wasn't clear enough.)

Can you clarify?

Thanks

**Comment by joshuaclayton** [comment]
@georgemillo ah, I see the confusion; I had made an assumption of what your expected ideal outcome is, and I'd definitely misread the approach you recommended. Apologies!

What I think would be impossible to do is determine in that conditional I'd linked to which option to take - specifically, it would modify behavior to choose the correct version of `present`.

Re-reading your comment, I do think your suggestion of raising when defining the trait (if a factory of the same name exists) or when defining the factory (if a trait of the same name, regardless of nesting, exists) is the appropriate step. That way, it can help guide the developer to the naming collision without ever allowing a confusing situation to occur, which is the behavior you've run into. Based on this, I think the most helpful error we can provide is that there's a naming collision during definition, but not that they've used something incorrectly.
