### ISSUE TITLE
Are factories created before the test suite is run

### ISSUE THREAD

**Issue by mrageh** [thoughtbot/factory_girl#906]
Hey 

I am working on a simple gem https://github.com/mrageh/slow_factory_formatter that prints a table containing the number of slow factories created when a test suite is run.

I was implementing a new feature that tracks the % of time a test suite spends setting up factories, by using `RSpec::Core::Notifications::SummaryNotification#duration`. 

I noticed something peculiar the time taken to setup my factories is always greater then time taken to run the test suite. 

When running a test suite in RSpec at what point are factories created/instantiated. Is it when RSpec is loading spec files and booting or when the test suite is run?

**Comment by joshuaclayton** [comment]
Hi @mrageh! I'm not super familiar with that duration calculation, but I can tell you that the AS::Instrumentation work that FG does internally *only* happens when one of the internal strategy methods are used (e.g. `build`, `create`, `build_list`, etc). I wonder if they're being run throughout the suite and that's why the total duration is the length of the suite.

It seems like you'd want to subscribe to `run_factory` (which I'm sure you're already doing), do the duration math there, and keep track of the total time, and compare that to the duration of the entire suite.

I haven't looked through your library but if you have a PR I could take a look at, I'd be happy to lend my eyes.

**Comment by mrageh** [comment]
Thanks for the swift response @joshuaclayton. 


> I wonder if they're being run throughout the suite and that's why the total duration is the length of the suite. 

I am not sure if that's the problem as the total factory setup time is greater than the duration that the test suite takes.

> It seems like you'd want to subscribe to run_factory (which I'm sure you're already doing), do the duration math there, and keep track of the total time, and compare that to the duration of the entire suite.

I believe that's what I am doing right now.

Here is the commit that introduces the new [functionality](https://github.com/mrageh/slow_factory_formatter/commit/9276de9db108dab0c660623a47c350573ce95536).

**Comment by joshuaclayton** [comment]
@mrageh apologies for the late reply here. Any updates or progress on this? With a lack of familiarity with the code, it's hard for me to provide help or guidance apart from suggesting inserting a `sleep(3)` or similar and seeing what happens here. If there's anything else I can do here to help, though, please let me know!

**Comment by mrageh** [comment]
Thanks for closing this issue Joshua, I don't think the problem is caused by FactoryGirl
