### ISSUE TITLE
Use trait in callback

### ISSUE THREAD

**Issue by ofetisov** [thoughtbot/factory_girl#946]
Hello guys, I'trying DRY my code with traits but I can't understand how to use traits in callbacks. Code below represents what i'm trying to do and obviously - doesn't works. Or maybe i'm using wrong approach?
```Ruby
FactoryGirl.define do
  trait :abc_t do
    abc true
   #lots of vars goes here
  end

  trait :abc_f do
    abc false
   #lots of vars goes here
  end

  factory :test, :class => Test do
    transient do
      some_var false
    end
   
    #some traits here

    after(:build) do |obj, evaluator|
      if evaluator.some_var
        abc_t
      else
        abc_f
      end
    end
  end
end
```

**Comment by joshuaclayton** [comment]
@ofetisov traits are unusable in callbacks - imagine it as a named block to refer to some attributes you'd assign in the factory itself.

If you're attempting to conditionally apply a trait, my recommendation would be to do so from the call site (where you call `create(:thing, :trait_1)`) instead of in the factory itself.
